include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - no_leading_underscores_for_local_identifiers
